easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Agency
        - App\Entity\Flight
        - App\Entity\Hotel
        - App\Entity\User

    design:
            brand_color: '#ff0015'
